info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api/v1/create:
    post:
      description: "\u0421\u043E\u0437\u0434\u0430\u043D\u0438\u0435 \u043F\u043E\u043B\
        \u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F"
      operationId: create_create
      tags:
      - create
  /api/v1/login:
    post:
      description: "\u0410\u0432\u0442\u043E\u0440\u0438\u0437\u0430\u0446\u0438\u044F\
        \ \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F\
        \n\u043D\u0435\u043E\u0431\u0445\u043E\u0434\u0438\u043C\u043E \u043E\u0442\
        \u043F\u0440\u0430\u0432\u0438\u0442\u044C json \u0432 Body \u0432\u0438\u0434\
        \u0430:\n\n{ \"email\": \"example@example.com\",\n  \"password\": \"123456\"\
        \n}"
      operationId: login_create
      tags:
      - login
  /api/v1/user/{id}:
    delete:
      description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u043E\u0442\
        \u0434\u0435\u043B\u044C\u043D\u043E\u0433\u043E \u043F\u043E\u043B\u044C\u0437\
        \u043E\u0432\u0430\u0442\u0435\u043B\u044F \u043F\u043E pk"
      operationId: user_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: "A unique integer value identifying this \u043F\u043E\u043B\
            \u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
          title: ID
          type: integer
      tags:
      - user
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u043E\u0442\
        \u0434\u0435\u043B\u044C\u043D\u043E\u0433\u043E \u043F\u043E\u043B\u044C\u0437\
        \u043E\u0432\u0430\u0442\u0435\u043B\u044F \u043F\u043E pk"
      operationId: user_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: "A unique integer value identifying this \u043F\u043E\u043B\
            \u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
          title: ID
          type: integer
      tags:
      - user
    patch:
      description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u043E\u0442\
        \u0434\u0435\u043B\u044C\u043D\u043E\u0433\u043E \u043F\u043E\u043B\u044C\u0437\
        \u043E\u0432\u0430\u0442\u0435\u043B\u044F \u043F\u043E pk"
      operationId: user_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: "A unique integer value identifying this \u043F\u043E\u043B\
            \u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
          title: ID
          type: integer
      tags:
      - user
    put:
      description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u043E\u0442\
        \u0434\u0435\u043B\u044C\u043D\u043E\u0433\u043E \u043F\u043E\u043B\u044C\u0437\
        \u043E\u0432\u0430\u0442\u0435\u043B\u044F \u043F\u043E pk"
      operationId: user_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: "A unique integer value identifying this \u043F\u043E\u043B\
            \u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
          title: ID
          type: integer
      tags:
      - user
  /api/v1/users:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u0441\u043F\
        \u0438\u0441\u043A\u0430 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\
        \u0435\u043B\u0435\u0439"
      operationId: users_list
      parameters:
      - in: query
        name: limit
        schema:
          description: Number of results to return per page.
          title: Limit
          type: integer
      - in: query
        name: offset
        schema:
          description: The initial index from which to return the results.
          title: Offset
          type: integer
      tags:
      - users
servers:
- url: ''
